In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([-0.62361855, -2.27794231, -0.13638854, -1.2678545 , -1.120573  ,
       -0.90560043,  1.14470925,  0.82829736,  0.64241673, -0.51209916])

In [6]:
B = np.random.randn(10)
B

array([-2.808306  ,  1.95461328, -0.99867422,  0.55991711,  0.95911036,
       -0.17357212, -1.06608327, -1.49086079,  0.61740283, -1.3793876 ])

In [7]:
# Binary Functions
np.add(A,B)

array([-3.43192454, -0.32332903, -1.13506276, -0.70793739, -0.16146265,
       -1.07917255,  0.07862598, -0.66256342,  1.25981956, -1.89148676])

In [9]:
np.maximum(A,B)
# Maximum will output the highest value of the params (comparing the params)

array([-0.62361855,  1.95461328, -0.13638854,  0.55991711,  0.95911036,
       -0.17357212,  1.14470925,  0.82829736,  0.64241673, -0.51209916])

In [13]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-unfuncs'
import webbrowser
webbrowser.open(website)

True