In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0  0.692911  1.975963  0.875920
1 -1.033008  0.593672  1.095947
2 -1.895551 -0.518719  1.304417
3  1.271429 -0.204716 -0.486808

In [14]:
dframe2

Y         Q         X
0  0.776517 -0.888564  1.555085
1  0.899161 -0.066798  0.066373
2  0.779923 -0.843909 -0.449981

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.692911  1.975963  0.875920
1       NaN -1.033008  0.593672  1.095947
2       NaN -1.895551 -0.518719  1.304417
3       NaN  1.271429 -0.204716 -0.486808
0 -0.888564  1.555085  0.776517       NaN
1 -0.066798  0.066373  0.899161       NaN
2 -0.843909 -0.449981  0.779923       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.692911  1.975963  0.875920
1       NaN -1.033008  0.593672  1.095947
2       NaN -1.895551 -0.518719  1.304417
3       NaN  1.271429 -0.204716 -0.486808
4 -0.888564  1.555085  0.776517       NaN
5 -0.066798  0.066373  0.899161       NaN
6 -0.843909 -0.449981  0.779923       NaN

In [17]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'